# .github/workflows/earthbeat.yml
name: Daily Earthbeat Entry

on:
  schedule:
    - cron: "30 7 * * *"   # 07:30 UTC daily
  workflow_dispatch: {}

jobs:
  add-earthbeat:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install system libs for canvas
        run: |
          sudo apt-get update
          sudo apt-get install -y libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev

      - name: Install dependencies
        run: npm ci

      - name: Append Earthbeat entry
        run: node scripts/addEarthbeat.js

      - name: Commit changes (if any)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add src/data/journalEntries.json public/earthbeat
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "chore(journal): add Earthbeat entry (auto)"
          git push
